export type AreaOfWork =
  | 'Information Technology (IT)'
  | 'UX/UI Design'
  | 'Communication'
  | 'Human Resources (HR)'
  | 'Finance'
  | 'Marketing'
  | 'Sales'
  | 'Customer Support'
  | 'Project Management'
  | 'Healthcare'
  | 'Education'
  | 'Engineering'
  | 'Legal'
  | 'Operations'
  | 'Logistics'
  | 'Manufacturing'

export const areasOfWork: Record<AreaOfWork, string[]> = {
  'Information Technology (IT)': [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Vue.js',
    'Angular',
    'Svelte',
    'Node.js',
    'Express.js',
    'NestJS',
    'Next.js',
    'Gatsby',
    'Nuxt.js',
    'Electron',
    'TypeScript',
    'Python',
    'Django',
    'Flask',
    'FastAPI',
    'Pandas',
    'NumPy',
    'SciPy',
    'TensorFlow',
    'Keras',
    'PyTorch',
    'Scikit-learn',
    'Java',
    'Spring Boot',
    'Quarkus',
    'Micronaut',
    'Hibernate',
    'Kotlin',
    'Scala',
    'Groovy',
    'C++',
    'Qt',
    'Boost',
    'C#',
    '.NET Core',
    'Xamarin',
    'Unity',
    'F#',
    'Rust',
    'Go',
    'Swift',
    'Objective-C',
    'iOS Development',
    'Android Development',
    'Kotlin Multiplatform',
    'Flutter',
    'React Native',
    'Xcode',
    'Android Studio',
    'Firebase',
    'Realm Database',
    'MongoDB',
    'SQL',
    'PostgreSQL',
    'MySQL',
    'SQLite',
    'Oracle DB',
    'Microsoft SQL Server',
    'Redis',
    'Cassandra',
    'DynamoDB',
    'GraphQL',
    'Apollo',
    'Relay',
    'REST API Development',
    'gRPC',
    'WebSockets',
    'RabbitMQ',
    'Kafka',
    'ActiveMQ',
    'Amazon Web Services (AWS)',
    'Microsoft Azure',
    'Google Cloud Platform (GCP)',
    'IBM Cloud',
    'Oracle Cloud',
    'Heroku',
    'Netlify',
    'Vercel',
    'Docker',
    'Kubernetes',
    'OpenShift',
    'Rancher',
    'Helm',
    'Terraform',
    'Ansible',
    'Chef',
    'Puppet',
    'Vagrant',
    'Jenkins',
    'GitLab CI/CD',
    'Travis CI',
    'CircleCI',
    'Bamboo',
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'Mercurial',
    'SVN',
    'Agile Methodologies',
    'Scrum',
    'Kanban',
    'SAFe (Scaled Agile Framework)',
    'Lean',
    'XP (Extreme Programming)',
    'JIRA',
    'Confluence',
    'Trello',
    'Asana',
    'Slack',
    'Microsoft Teams',
    'Zoom',
    'VS Code',
    'Sublime Text',
    'Atom',
    'IntelliJ IDEA',
    'PyCharm',
    'WebStorm',
    'CLion',
    'Eclipse',
    'NetBeans',
    'Android Development',
    'iOS Development',
    'Cross-platform Development',
    'Machine Learning',
    'Deep Learning',
    'AI',
    'Computer Vision',
    'Data Science',
    'Data Engineering',
    'Big Data',
    'Hadoop',
    'Spark',
    'Flink',
    'Hive',
    'Pig',
    'Cassandra',
    'ElasticSearch',
    'Logstash',
    'Kibana',
    'Grafana',
    'Prometheus',
    'Splunk',
    'Graylog',
    'Datadog',
    'New Relic',
    'ELK Stack',
    'DevOps',
    'SecOps',
    'DevSecOps',
    'Cloud Security',
    'Penetration Testing',
    'Ethical Hacking',
    'OWASP',
    'Blockchain',
    'Crypto Wallets',
    'Unity',
    'Animation',
    'Rendering',
    'Cybersecurity',
    'Cryptography',
    'SSL/TLS',
    'Public Key Infrastructure (PKI)',
    'Secure Coding Practices',
    'Code Review',
    'Static Analysis',
    'Dynamic Analysis',
    'Software Testing',
    'Unit Testing',
    'Integration Testing',
    'System Testing',
    'Acceptance Testing',
    'Test Automation',
    'Selenium',
    'Cypress',
    'TestNG',
    'JUnit',
    'Mockito',
    'TDD (Test-Driven Development)',
    'BDD (Behavior-Driven Development)',
    'Cucumber',
    'Stress Testing',
    'Security Testing',
    'Compliance Testing',
    'Accessibility Testing',
    'Postman',
    'SoapUI',
    'RestAssured',
    'Swagger',
    'WireMock',
    'Pact',
    'UI/UX Design',
    'Wireframing',
    'Prototyping',
    'User Research',
    'User Testing',
    'Usability Testing',
    'A/B Testing',
    'Responsive Design',
    'Mobile-First Design',
    'Interaction Design',
    'Visual Design',
    'Accessibility',
    'Branding',
    'Design Systems',
    'Material Design',
    'Motion Design',
    'Service Design',
    'Content Strategy',
    'SEO (Search Engine Optimization)',
    'SEM (Search Engine Marketing)',
    'Analytics',
    'Power BI',
    'Data Warehousing',
    'Snowflake',
    'Redshift',
    'BigQuery',
    'IoT (Internet of Things)',
    'Chatbots',
  ],
  'UX/UI Design': [
    'Figma',
    'Adobe XD',
    'Sketch',
    'Photoshop',
    'Illustrator',
    'CorelDRAW',
    'Lottie',
    'Wireframing',
    'Prototyping',
    'User Research',
    'Usability Testing',
  ],
  Communication: [
    'Social Media Management',
    'Instagram',
    'Facebook',
    'LinkedIn',
    'Twitter',
    'Content Creation',
    'Paid Traffic',
    'Filmmaker',
    'Photography',
    'Video Editing',
    'Copywriting',
    'Public Relations',
    'Crisis Communication',
  ],
  'Human Resources (HR)': [
    'People Management',
    'Recruitment',
    'Employee Relations',
    'Performance Management',
    'Training and Development',
    'Payroll Management',
    'HR Software',
    'Time Tracking',
    'Employee Engagement',
    'Organizational Development',
  ],
  Finance: [
    'Accounting',
    'Financial Analysis',
    'Budgeting',
    'Forecasting',
    'Auditing',
    'Taxation',
    'Financial Reporting',
    'Risk Management',
    'Investment Management',
    'Corporate Finance',
    'SAP',
    'QuickBooks',
    'Excel',
  ],
  Marketing: [
    'SEO',
    'SEM',
    'Content Marketing',
    'Email Marketing',
    'Social Media Marketing',
    'Market Research',
    'Brand Management',
    'Digital Marketing',
    'Google Analytics',
    'HubSpot',
    'Salesforce',
    'Copywriting',
    'Campaign Management',
  ],
  Sales: [
    'Lead Generation',
    'Sales Strategy',
    'Customer Relationship Management (CRM)',
    'Negotiation',
    'Salesforce',
    'Cold Calling',
    'Account Management',
    'Sales Pitching',
    'Retail Sales',
    'B2B Sales',
    'B2C Sales',
    'Customer Retention',
  ],
  'Customer Support': [
    'Customer Service',
    'Technical Support',
    'Help Desk',
    'Client Relations',
    'CRM Software',
    'Zendesk',
    'Live Chat Support',
    'Phone Support',
    'Complaint Resolution',
    'Service Level Agreement (SLA)',
  ],
  'Project Management': [
    'Project Planning',
    'Agile Methodologies',
    'Scrum',
    'Kanban',
    'Project Scheduling',
    'Risk Management',
    'Resource Management',
    'MS Project',
    'JIRA',
    'Trello',
    'Asana',
    'Stakeholder Management',
  ],
  Healthcare: [
    'Patient Care',
    'Clinical Research',
    'Healthcare Administration',
    'Electronic Health Records (EHR)',
    'Medical Coding',
    'Patient Communication',
    'Medical Ethics',
    'HIPAA Compliance',
    'Telemedicine',
    'Phlebotomy',
  ],
  Education: [
    'Curriculum Development',
    'Classroom Management',
    'Educational Technology',
    'Online Teaching',
    'Lesson Planning',
    'Assessment and Evaluation',
    'Special Education',
    'Student Counseling',
    'Teaching Strategies',
    'Learning Management Systems (LMS)',
  ],
  Engineering: [
    'Mechanical Engineering',
    'Electrical Engineering',
    'Civil Engineering',
    'Structural Analysis',
    'AutoCAD',
    'SolidWorks',
    'MATLAB',
    'Project Engineering',
    'Lean Manufacturing',
    'Six Sigma',
  ],
  Legal: [
    'Legal Research',
    'Contract Law',
    'Corporate Law',
    'Intellectual Property',
    'Litigation',
    'Legal Writing',
    'Case Management',
    'Compliance',
    'Paralegal',
    'Legal Ethics',
  ],
  Operations: [
    'Operational Efficiency',
    'Process Improvement',
    'Lean Manufacturing',
    'Six Sigma',
    'Supply Chain Management',
    'Quality Control',
    'Inventory Management',
    'Production Planning',
    'Operations Management',
    'Workflow Optimization',
  ],
  Logistics: [
    'Supply Chain Management',
    'Inventory Control',
    'Warehouse Management',
    'Transportation Management',
    'Logistics Planning',
    'Import/Export Management',
    'Freight Forwarding',
    'Fleet Management',
    'Logistics Software',
    'Distribution Management',
  ],
  Manufacturing: [
    'Production Management',
    'Quality Assurance',
    'Lean Manufacturing',
    'Six Sigma',
    'Process Optimization',
    'Machining',
    'Industrial Safety',
    'Supply Chain Management',
    'Logistics',
    'Inventory Control',
  ],
}
