import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '../ui/accordion'

const faqItems = [
  {
    trigger: 'How do I create a PDF using this tool?',
    content:
      'To create a PDF using our tool, simply create an account, insert your information or upload the PDF generated by LinkedIn. Once you&rsquo;ve reviewed your details, you can download the final PDF with just a click.',
    value: 'item-1',
  },
  {
    trigger: 'Is the service really free?',
    content:
      'Yes, our service is completely free to use. There are no hidden costs or fees. However, if you find the service helpful and would like to support us, you can make a donation to help keep the project running.',
    value: 'item-2',
  },
  {
    trigger: 'What file formats are supported for conversion?',
    content:
      'Currently, our tool only supports PDFs generated by LinkedIn. We&rsquo;re working on expanding file format support in the future.',
    value: 'item-3',
  },
  {
    trigger: 'Is my data secure when using this service?',
    content:
      'Yes, your data is secure. We only use your information to store the history of your PDF creations. All user data is securely managed through Clerk, ensuring your privacy is maintained.',
    value: 'item-4',
  },
  {
    trigger: 'Can I use this tool on mobile devices?',
    content:
      'Yes, our site is fully responsive and optimized for mobile devices, so you can easily use it on your smartphone or tablet.',
    value: 'item-5',
  },
]

function FAQSection() {
  return (
    <section id="faq">
      <header>
        <h2 className="py-6 text-center text-3xl font-bold text-dark-blue dark:text-light-gray">
          Frequently Asked Questions
        </h2>
      </header>
      <Accordion type="single" collapsible className="w-full">
        {faqItems.map((item) => (
          <AccordionItem key={item.value} value={item.value}>
            <AccordionTrigger>{item.trigger}</AccordionTrigger>
            <AccordionContent>{item.content}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </section>
  )
}

export default FAQSection
