export { default as HeroSection } from './hero.section'
export { default as OurFeaturesSection } from './our-features.section'
export { default as StatisticsSection } from './statistics.section'
export { default as PricingSection } from './pricing.section'
export { default as TestimonialsSection } from './testimonials.section'
